name: Workflow SHA Inputs

on:
  workflow_dispatch:
    inputs:
      sha:
        required: true
        type: string
        description: "sha"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.event.inputs.sha }}
    steps:
      - name: Execute
        run: echo executing $SHA
