name: Workflow SHA Inputs

on:
  workflow_dispatch:
    inputs:
      sha:
        required: true
        type: string
        description: "sha"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute
        run: echo "${{ inputs.sha }}"
