name: Deploy to Production (Force)

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short ${{ github.sha }})"

      - name: Execute
        run: echo "${{ steps.vars.outputs.sha_short }}"
