name: Workflow Test If Success

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Exit
        run: |
          echo "exiting with non (success)"
          exit 1
      - name: Does this still run
        run: |
          echo "if this runs we have a problem"
          exit 1
      - name:
        if: ${{ success() }}
        run: |
          echo "if this runs then we really have problem"
          exit 0
